/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnisimulator_DiceWrapper */

#ifndef _Included_jnisimulator_DiceWrapper
#define _Included_jnisimulator_DiceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnisimulator_DiceWrapper
 * Method:    getTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_DiceWrapper_getTime
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_DiceWrapper
 * Method:    performOneStepOfSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisimulator_DiceWrapper_performOneStepOfSimulation
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_DiceWrapper
 * Method:    performWholeSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisimulator_DiceWrapper_performWholeSimulation
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_DiceWrapper
 * Method:    setSimulatorForNewSimulation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnisimulator_DiceWrapper_setSimulatorForNewSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_DiceWrapper
 * Method:    rval
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_DiceWrapper_rval__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_DiceWrapper
 * Method:    rval
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_DiceWrapper_rval__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
