/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnisimulator_CoinFlipWrapper */

#ifndef _Included_jnisimulator_CoinFlipWrapper
#define _Included_jnisimulator_CoinFlipWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    setBias
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jnisimulator_CoinFlipWrapper_setBias
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    getTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_CoinFlipWrapper_getTime
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    performOneStepOfSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisimulator_CoinFlipWrapper_performOneStepOfSimulation
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    performWholeSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisimulator_CoinFlipWrapper_performWholeSimulation
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    setSimulatorForNewSimulation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnisimulator_CoinFlipWrapper_setSimulatorForNewSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    rval
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_CoinFlipWrapper_rval__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_CoinFlipWrapper
 * Method:    rval
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_CoinFlipWrapper_rval__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
