/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnisimulator_ServerWrapper */

#ifndef _Included_jnisimulator_ServerWrapper
#define _Included_jnisimulator_ServerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    getTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_ServerWrapper_getTime
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    performOneStepOfSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisimulator_ServerWrapper_performOneStepOfSimulation
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    performWholeSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisimulator_ServerWrapper_performWholeSimulation
  (JNIEnv *, jobject);

/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    setMaxNumberOfEvents
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnisimulator_ServerWrapper_setMaxNumberOfEvents
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    setSimulatorForNewSimulation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnisimulator_ServerWrapper_setSimulatorForNewSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    rval
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_ServerWrapper_rval__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnisimulator_ServerWrapper
 * Method:    rval
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jnisimulator_ServerWrapper_rval__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
