/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mock_DiceWrapper */

#ifndef _Included_mock_DiceWrapper
#define _Included_mock_DiceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mock_DiceWrapper
 * Method:    getTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_mock_DiceWrapper_getTime
  (JNIEnv *, jobject);

/*
 * Class:     mock_DiceWrapper
 * Method:    performOneStepOfSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mock_DiceWrapper_performOneStepOfSimulation
  (JNIEnv *, jobject);

/*
 * Class:     mock_DiceWrapper
 * Method:    performWholeSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mock_DiceWrapper_performWholeSimulation
  (JNIEnv *, jobject);

/*
 * Class:     mock_DiceWrapper
 * Method:    setSimulatorForNewSimulation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mock_DiceWrapper_setSimulatorForNewSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     mock_DiceWrapper
 * Method:    rval
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_mock_DiceWrapper_rval__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     mock_DiceWrapper
 * Method:    rval
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_mock_DiceWrapper_rval__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
