/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_SimulatorState */

#ifndef _Included_test_SimulatorState
#define _Included_test_SimulatorState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_SimulatorState
 * Method:    getTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_test_SimulatorState_getTime
  (JNIEnv *, jobject);

/*
 * Class:     test_SimulatorState
 * Method:    performOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_SimulatorState_performOne
  (JNIEnv *, jobject);

/*
 * Class:     test_SimulatorState
 * Method:    performWhole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_SimulatorState_performWhole
  (JNIEnv *, jobject);

/*
 * Class:     test_SimulatorState
 * Method:    setSimulator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_test_SimulatorState_setSimulator
  (JNIEnv *, jobject, jint);

/*
 * Class:     test_SimulatorState
 * Method:    printrval
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_test_SimulatorState_printrval__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     test_SimulatorState
 * Method:    printrval
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_test_SimulatorState_printrval__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
